### ISSUE TITLE
DAHDI for conferencing?

### ISSUE THREAD

**Issue by joshuacox** [xivo-pbx/dahdi-tools#2]
When Joining a conference that has the `Record name and announce join/leaves` enabled I get this error:
```
app_meetme.c: No DAHDI channel available for conference, user introduction disabled (is chan_dahdi loaded?)
```

It seems most of the threads on this topic are very old, so I thought I'd ask here.

I'm using a freshly installed from iso XIVO `Version: 16.06 "Five"`

**Comment by sboily** [comment]
Hello, it seems you haven't dahdi loaded. Can you use our forum for request help ?

http://projects.xivo.io/projects/xivo/boards

Can you show us the output of a dmesg ?

Thank you!

**Comment by joshuacox** [comment]
sure here's a sprunge:

http://sprunge.us/SWKT

**Comment by joshuacox** [comment]
opened in redmine there:
http://projects.xivo.io/boards/1/topics/6054

closing here
